package TUD;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class WyrobManager {
	private Connection connection;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private String createTableWyrob = "CREATE TABLE Wyrob_cukierniczy(id bigint GENERATED BY DEFAULT AS IDENTITY, nazwa varchar(50), cena double)";
	
	private PreparedStatement DodajWyrob;
	private PreparedStatement UsunWyroby;
	private PreparedStatement GetWyroby;
	
	private Statement statement;
	
	public WyrobManager(){
		try{
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("Wyrob_cukierniczy".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists = true;
					break;
					
				}
			}
			
			if(!tableExists)
				statement.executeUpdate(createTableWyrob);
			
			DodajWyrob = connection.prepareStatement("INSERT INTO Wyrob_cukierniczy(nazwa, cena) VALUES (?, ?)");
			UsunWyroby = connection.prepareStatement("DELETE FROM Wyrob_cukierniczy");
			GetWyroby = connection.prepareStatement("SELECT id, nazwa, cena FROM Wyrob_cukierniczy");
			
		} catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	Connection getConnection(){
		return connection;
	}
	
	void wyczyscWyroby(){
		try{
			UsunWyroby.executeUpdate();
		} catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	public int dodajWyrob(Wyrob_cukierniczy wyrob){
		int count = 0;
		try {
			DodajWyrob.setString(1, wyrob.getNazwa());
			DodajWyrob.setDouble(2, wyrob.getCena());
			
			count = DodajWyrob.executeUpdate();
		} catch(SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public List<Wyrob_cukierniczy> getWyroby(){
		List<Wyrob_cukierniczy> wyroby = new ArrayList<Wyrob_cukierniczy>();
		
		try{
			ResultSet rs = GetWyroby.executeQuery();
			
			while(rs.next()){
				Wyrob_cukierniczy w = new Wyrob_cukierniczy();
				w.setId(rs.getInt("id"));
				w.setNazwa(rs.getString("nazwa"));
				w.setCena(rs.getDouble("cena"));
				wyroby.add(w);
			}
		} catch(SQLException e){
			e.printStackTrace();
		}
		return wyroby;
	}
}
