package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class WyrobManager {
	private Connection connection;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private String createTableWyrob = "CREATE TABLE WyrobCukierniczy(id_wyrob bigint GENERATED BY DEFAULT AS IDENTITY, nazwa varchar(50), cena varchar(5))";
	
	private PreparedStatement DodajWyrob;
	private PreparedStatement UsunWyroby;
	private PreparedStatement GetWyroby;
	
	private Statement statement;
	
	public WyrobManager(){
		try{
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("WyrobCukierniczy".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists = true;
					break;
					
				}
			}
			
			if(!tableExists)
				statement.executeUpdate(createTableWyrob);
			
			DodajWyrob = connection.prepareStatement("INSERT INTO WyrobCukierniczy(nazwa, cena) VALUES (?, ?)");
			UsunWyroby = connection.prepareStatement("DELETE FROM WyrobCukierniczy");
			GetWyroby = connection.prepareStatement("SELECT id_wyrob, nazwa, cena FROM WyrobCukierniczy");
			
		} catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	public Connection getConnection(){
		return connection;
	}
	
	public void wyczyscWyroby(){
		try{
			UsunWyroby.executeUpdate();
		} catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	public int dodajWyrob(WyrobCukierniczy wyrob){
		int count = 0;
		try {
			DodajWyrob.setString(1, wyrob.getNazwa());
			DodajWyrob.setString(2, wyrob.getCena());
			
			count = DodajWyrob.executeUpdate();
		} catch(SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public List<WyrobCukierniczy> getWyroby(){
		List<WyrobCukierniczy> wyroby = new ArrayList<WyrobCukierniczy>();
		
		try{
			ResultSet rs = GetWyroby.executeQuery();
			
			while(rs.next()){
				WyrobCukierniczy w = new WyrobCukierniczy();
				w.setId(rs.getInt("id_wyrob"));
				w.setNazwa(rs.getString("nazwa"));
				w.setCena(rs.getString("cena"));
				wyroby.add(w);
			}
		} catch(SQLException e){
			e.printStackTrace();
		}
		return wyroby;
	}
}
