package main;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class ZamowienieManager {
	private Connection connection;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private String createTableZamowienie = "CREATE TABLE Zamowienie(id_zamowienie bigint GENERATED BY DEFAULT AS IDENTITY, waga double, data Date)";

	
	private PreparedStatement DodajZamowienie;
	private PreparedStatement UsunZamowienie;
	private PreparedStatement GetZamowienie;
	
	private Statement statement;
	
	public ZamowienieManager(){
		try{
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("Zamowienie".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists = true;
					break;
					
				}
			}
			
			if(!tableExists)
				statement.executeUpdate(createTableZamowienie);
			
			DodajZamowienie = connection.prepareStatement("INSERT INTO Zamowienie(waga, data) VALUES (?, ?)");
			UsunZamowienie = connection.prepareStatement("DELETE FROM Zamowienie");
			GetZamowienie = connection.prepareStatement("SELECT id_zamowienie, waga, data FROM Zamowienie");
			
		} catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	Connection getConnection(){
		return connection;
	}
	
	void wyczyscZamowienia(){
		try{
			UsunZamowienie.executeUpdate();
		} catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	public int dodajZamowienie(Zamowienie zamowienie){
		int count = 0;
		try {
			DodajZamowienie.setDouble(1, zamowienie.getWaga());
			DodajZamowienie.setDate(2, (Date) zamowienie.getData());
			
			count = DodajZamowienie.executeUpdate();
		} catch(SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public List<Zamowienie> getWyroby(){
		List<Zamowienie> zamowienia = new ArrayList<Zamowienie>();
		
		try{
			ResultSet rs = GetZamowienie.executeQuery();
			
			while(rs.next()){
				Zamowienie z = new Zamowienie();
				z.setId(rs.getInt("id_zamowienie"));
				z.setWaga(rs.getDouble("waga"));
				z.setData(rs.getDate("data"));
				zamowienia.add(z);
			}
		} catch(SQLException e){
			e.printStackTrace();
		}
		return zamowienia;
	}
}